-- FIND EMPLOYEES WITH EXPENSES EXCEEDING 1000

-- TO CALCULATE TOTAL EXPENSES PER EMPLOYEE
WITH TOTALEXPENSES AS (
    SELECT 
        E.EMPLOYEE_ID, 
        CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS EMPLOYEE_NAME,
        E.MANAGER_ID,
        SUM(EX.UNIT_PRICE * EX.QUANTITY) AS TOTAL_EXPENSED_AMOUNT
    FROM MEMORY.DEFAULT.EMPLOYEE E
    JOIN MEMORY.DEFAULT.EXPENSE EX ON E.EMPLOYEE_ID = EX.EMPLOYEE_ID
    GROUP BY E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.MANAGER_ID
),

-- TO GET MANAGER NAMES
MANAGERS AS (
    SELECT 
        EMPLOYEE_ID AS MANAGER_ID,
        CONCAT(FIRST_NAME, ' ', LAST_NAME) AS MANAGER_NAME
    FROM MEMORY.DEFAULT.EMPLOYEE
)

-- SELECT EMPLOYEES WITH HIGH EXPENSES
SELECT 
    TE.EMPLOYEE_ID, 
    TE.EMPLOYEE_NAME, 
    TE.MANAGER_ID, 
    M.MANAGER_NAME, 
    TE.TOTAL_EXPENSED_AMOUNT
FROM TOTALEXPENSES TE
JOIN MANAGERS M ON TE.MANAGER_ID = M.MANAGER_ID
WHERE TE.TOTAL_EXPENSED_AMOUNT > 1000
ORDER BY TE.TOTAL_EXPENSED_AMOUNT DESC;
