-- CREATE THE INVOICE TABLE
CREATE TABLE MEMORY.DEFAULT.INVOICE (
    SUPPLIER_ID TINYINT,
    INVOICE_AMOUNT DECIMAL(8, 2),
    DUE_DATE DATE
);

-- CREATE THE SUPPLIER TABLE
CREATE TABLE MEMORY.DEFAULT.SUPPLIER (
    SUPPLIER_ID TINYINT,
    NAME VARCHAR
);

-- INSERT SUPPLIER DATA INTO THE SUPPLIER TABLE
INSERT INTO MEMORY.DEFAULT.SUPPLIER (SUPPLIER_ID, NAME) VALUES 
(1, 'Brilliant Bottles'), 
(2, 'Catering Plus'), 
(3, 'Dave''s Discos'), 
(4, 'Entertainment tonight'), 
(5, 'Ice Ice Baby'), 
(6, 'Party Animals');

-- INSERT INVOICE DATA INTO THE INVOICE TABLE
INSERT INTO MEMORY.DEFAULT.INVOICE (SUPPLIER_ID, INVOICE_AMOUNT, DUE_DATE) VALUES 
(6, 6000.0, LAST_DAY_OF_MONTH(CURRENT_DATE + INTERVAL '3' MONTH)), 
(2, 2000.0, LAST_DAY_OF_MONTH(CURRENT_DATE + INTERVAL '2' MONTH)), 
(2, 1500.0, LAST_DAY_OF_MONTH(CURRENT_DATE + INTERVAL '3' MONTH)), 
(3, 500.0, LAST_DAY_OF_MONTH(CURRENT_DATE + INTERVAL '1' MONTH)), 
(4, 6000.0, LAST_DAY_OF_MONTH(CURRENT_DATE + INTERVAL '3' MONTH)), 
(5, 4000.0, LAST_DAY_OF_MONTH(CURRENT_DATE + INTERVAL '6' MONTH));
