-- AGGREGATE MANAGED EMPLOYEES FOR EACH EMPLOYEE

-- SELECT EMPLOYEE ID AND AGGREGATED LIST OF EMPLOYEES THEY MANAGE
SELECT 
    EMPLOYEE_ID, 
    ARRAY_AGG(NEXT) AS LOOP
FROM (
    -- INNER SELECT: JOIN EMPLOYEES WITH THEIR MANAGERS
    SELECT 
        L1.EMPLOYEE_ID, 
        L2.EMPLOYEE_ID AS NEXT
    FROM 
        MEMORY.DEFAULT.EMPLOYEE AS L1
    LEFT JOIN 
        MEMORY.DEFAULT.EMPLOYEE AS L2
    ON 
        L1.EMPLOYEE_ID = L2.MANAGER_ID
) AS SUBQUERY
GROUP BY 
    EMPLOYEE_ID
ORDER BY 
    EMPLOYEE_ID;
